site_name: Farm HPC Documentation
#site_url: http://docs.franklin.hpc.ucdavis.edu
repo_url: https://github.com/ctb/farm-docs
copyright: Copyright &copy; 2023-2024 The Regents of the University of California, Davis

nav:
  - About:
    - index.md
    - What farm can be used for: use-cases.md
  - User Guides:
    - guides/index.md
    - Getting an account: guides/signing-up.md
    - Starting RStudio Server: guides/rstudio.md
    - Installing your own R packages: guides/r-stats.md
    - Starting JupyterLab: guides/jupyter.md
    - Installing your own Python packages: guides/python.md
    - Using and installing command line software: guides/command-line.md
    - Viewing and uploading files on farm: guides/files.md
  - Reference Material and Tutorials:
    - reference/index.md
    - Generating and using an SSH key: reference/ssh-keys.md
    - Creating a conda/mamba environment: reference/conda.md

markdown_extensions:
  - toc:
      permalink: true
  - def_list
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: material/email-edit
      link: "mailto:farm-hpc@ucdavis.edu"
      name: Email Farm Support
    - icon: fontawesome/brands/slack
      link: https://ucdavis.slack.com/archives/C053NKA88
      name: "#hpc Channel on ucdavis.slack.com"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - javascripts/mathjax.js

theme:
  name: material
  features:
    - content.code.annotate
    #- navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  logo: assets/HPCCF-logo-dark.png
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - scheme: ucdavis
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
